version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "go"

  
  - package-ecosystem: "pub"
    directory: "/mimic_app"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "flutter"

  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "ci"