/// Mimic SDK Service - Bridges Flutter with Go Mobile SDK
///
/// This service provides the interface to the native Go Mobile library
/// using platform channels. The Go code is compiled via gomobile bind
/// and embedded in the Android/iOS applications.
library;

import 'dart:async';
import 'package:flutter/services.dart';
import '../models/network_stats.dart';

/// MimicClient - Wrapper for Go Mobile MimicClient using platform channels
///
/// The Go mobile bindings are generated by gomobile and embedded in
/// the native Android (aar) and iOS (xcframework) builds.
class MimicMobileClient {
  static MimicMobileClient? _instance;
  
  static MimicMobileClient get instance {
    _instance ??= MimicMobileClient._();
    return _instance!;
  }
  
  MimicMobileClient._();
  
  /// Platform channel for communicating with native Go code
  static const MethodChannel _channel = MethodChannel('com.locon213.mimic/sdk');
  
  /// Connection status codes (must match Go mobile.ConnectionStatus)
  static const int statusDisconnected = 0;
  static const int statusConnecting = 1;
  static const int statusConnected = 2;
  static const int statusReconnecting = 3;
  
  int _status = statusDisconnected;
  String? _serverUrl;
  String? _serverName;
  String _mode = 'TUN';
  NetworkStats _stats = NetworkStats();
  Function(NetworkStats)? _statsCallback;
  Timer? _statsTimer;
  StreamSubscription? _eventSubscription;
  
  /// Connect to a Mimic server
  /// 
  /// [serverUrl] - The mimic:// URL to connect to
  /// [mode] - Connection mode ('Proxy' or 'TUN')
  Future<void> connect(String serverUrl, String mode) async {
    _serverUrl = serverUrl;
    _mode = mode;
    _status = statusConnecting;
    _serverName = _extractServerName(serverUrl);
    
    try {
      // Call native Go code via platform channel
      await _channel.invokeMethod('connect', {
        'url': serverUrl,
        'mode': mode,
      });
      
      _status = statusConnected;
      _startStatsPolling();
    } catch (e) {
      // Native implementation not available, use mock
      await _mockConnect(serverUrl, mode);
    }
  }
  
  /// Mock connection for development (before gomobile bindings are ready)
  Future<void> _mockConnect(String serverUrl, String mode) async {
    // Simulate connection delay
    await Future.delayed(const Duration(seconds: 2));
    
    _status = statusConnected;
    _startStatsPolling();
  }
  
  /// Disconnect from the server
  Future<void> disconnect() async {
    _stopStatsPolling();
    
    try {
      await _channel.invokeMethod('disconnect');
    } catch (e) {
      // Native not available, just update local state
    }
    
    _status = statusDisconnected;
    _stats = NetworkStats();
  }
  
  /// Check if connected
  bool isConnected() => _status == statusConnected;
  
  /// Get current status
  int getStatus() => _status;
  
  /// Get status as string
  String getStatusString() {
    switch (_status) {
      case statusConnected:
        return 'connected';
      case statusConnecting:
        return 'connecting';
      case statusReconnecting:
        return 'reconnecting';
      default:
        return 'disconnected';
    }
  }
  
  /// Get current stats
  NetworkStats getStats() => _stats;
  
  /// Get server name
  String? getServerName() => _serverName;
  
  /// Get server URL
  String? getServerUrl() => _serverUrl;
  
  /// Set stats callback
  void setStatsCallback(Function(NetworkStats) callback) {
    _statsCallback = callback;
  }
  
  String _extractServerName(String url) {
    final hashParts = url.split('#');
    if (hashParts.length > 1) {
      return hashParts[1];
    }
    final atParts = url.split('@');
    if (atParts.length > 1) {
      final hostPart = atParts[1];
      final endIdx = hostPart.indexOf('?');
      if (endIdx != -1) {
        return hostPart.substring(0, endIdx);
      }
      return hostPart;
    }
    return 'Unknown Server';
  }
  
  /// Poll stats from native side every second
  void _startStatsPolling() {
    _stopStatsPolling();
    
    _statsTimer = Timer.periodic(const Duration(seconds: 1), (timer) async {
      if (_status != statusConnected) {
        timer.cancel();
        return;
      }
      
      try {
        final result = await _channel.invokeMapMethod<String, dynamic>('getStats');
        if (result != null) {
          _stats = NetworkStats(
            downloadSpeed: result['downloadSpeed'] as int? ?? 0,
            uploadSpeed: result['uploadSpeed'] as int? ?? 0,
            ping: result['ping'] as int? ?? 0,
            totalDownload: result['totalDownload'] as int? ?? 0,
            totalUpload: result['totalUpload'] as int? ?? 0,
          );
          _statsCallback?.call(_stats);
        }
      } catch (e) {
        // Native not available, use mock stats
        _updateMockStats();
      }
    });
  }
  
  void _stopStatsPolling() {
    _statsTimer?.cancel();
    _statsTimer = null;
  }
  
  /// Generate mock stats for development
  int _totalDownload = 0;
  int _totalUpload = 0;
  
  void _updateMockStats() {
    final downloadSpeed = 1024 * 100 + (DateTime.now().millisecond * 100);
    final uploadSpeed = 512 * 100 + (DateTime.now().millisecond * 50);

    _totalDownload += downloadSpeed;
    _totalUpload += uploadSpeed;

    _stats = NetworkStats(
      downloadSpeed: downloadSpeed,
      uploadSpeed: uploadSpeed,
      ping: 20 + (DateTime.now().millisecond % 30),
      totalDownload: _totalDownload,
      totalUpload: _totalUpload,
    );

    _statsCallback?.call(_stats);
  }
}
