name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: MimicClient-Windows.exe
            goos: windows
            goarch: amd64
          - os: ubuntu-latest
            artifact_name: MimicClient-Linux
            goos: linux
            goarch: amd64
          - os: macos-latest
            artifact_name: MimicClient-macOS
            goos: darwin
            goarch: amd64
          - os: ubuntu-latest
            artifact_name: MimicClient-Android.apk
            goos: android
            goarch: arm64

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Set up Fyne dependencies (Linux only)
        if: runner.os == 'Linux' && matrix.goos != 'android'
        run: sudo apt-get update && sudo apt-get install -y gcc libgl1-mesa-dev xorg-dev

      - name: Install Fyne CLI
        run: go install fyne.io/tools/cmd/fyne@latest

      - name: Build Application
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          if [ "${{ matrix.goos }}" == "android" ]; then
            fyne package -release -icon assets/icon.png -appID com.locon213.mimicapp -name MimicClient -os android
          else
            fyne package -release -icon assets/icon.png -appID com.locon213.mimicapp -name MimicClient -os ${{ matrix.goos }}
          fi
        if: runner.os != 'Windows'
        
      - name: Build Application (Windows)
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          fyne package -release -icon assets/icon.png -appID com.locon213.mimicapp -name MimicClient.exe -os ${{ matrix.goos }}
        if: runner.os == 'Windows'

      - name: Prepare Artifact
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            mv MimicClient.exe ${{ matrix.artifact_name }}
          elif [ "${{ matrix.goos }}" == "android" ]; then
            mv MimicClient.apk ${{ matrix.artifact_name }}
          elif [ "${{ runner.os }}" == "macOS" ]; then
            tar -czvf ${{ matrix.artifact_name }}.tar.gz MimicClient.app
          else
            tar -czvf ${{ matrix.artifact_name }}.tar.gz MimicClient.tar.xz
          fi
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: |
            ${{ matrix.artifact_name }}
            ${{ matrix.artifact_name }}.tar.gz
